[project]
name = "yawbdl"
version = "1.0.1"
description = "A tool to download pages from Internet Archive."
authors = [
    {name = "BGforge", email = "dev@bgforge.net"}
]
keywords = ["Internet Archive", "web.archive.org"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.4",
]

[project.urls]
Homepage = "https://github.com/BGforgeNet/yawbdl"
Repository = "https://github.com/BGforgeNet/yawbdl"

[dependency-groups]
dev = [
    "pylint>=3.3.7",
    "ruff>=0.12.2",
]
