# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Publish to PyPi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          uv build
          uv publish
