# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# For non-uv users

name: Update requirements.txt

on:
  push:
    branches:
      - "**"
    paths:
      - "uv.lock"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Update requirements.txt
        run: |
          uv export --no-hashes --format requirements-txt --no-dev > requirements.txt

      - uses: EndBug/add-and-commit@v9
        with:
          add: requirements.txt
          message: Updated requirements.txt
          default_author: github_actions
