# for non-poetry users

name: Update requirements.txt

on:
  push:
    paths:
      - "poetry.lock"
      - "pyproject.toml"

defaults:
  run:
    shell: bash # snok/install-poetry requirement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4

      - name: Load cached Poetry installation
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-1 # increment to reset cache

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-in-project: true

      - name: Update requirements.txt
        run: |
          poetry export -f requirements.txt -o requirements.txt --without-hashes
          poetry export -f requirements.txt -o requirements-dev.txt --without-hashes --with dev

      - uses: EndBug/add-and-commit@v9
        with:
          add: "requirements.txt requirements-dev.txt"
          message: "Updated requirements.txt"
          default_author: github_actions
